## traefik.yml
serversTransport:
  insecureSkipVerify: true
  MaxIdleConnsPerHost: 20000
  forwardingTimeouts:
    idleConnTimeout: 1s

entryPoints:
  web:
    address: ":8080"

providers:
  file:
    filename: /etc/traefik/host.yml
